server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iuuui_db?useunicode=true&amp;characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: iuuui
      password: Iuuui
mybatis:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml

